#!/bin/sh
#%SUMMARY: entry point to commands aggregator -- updates DB, completes input, and runs scripts
#%USAGE:(parallel): $ export WIW_CACHE_DIR="$(wiw --recache)"; parallel wiw ...
#%NOTE: redirects all long options directly to "cli" (e.g. completion requests from other exe)
#%PERF: cli=35ms next=8ms
set -eu

# IDEA: system-wide simplicity
#  * directly use PATH instead of XDG_LIBEXEC_PATH
#  * discoverability is achieved by standard shell facilities
#  * recaching is not needed -- kernel will search PATH each time
#  * if recaching is still needed -- you may call it explicitly in prolog of each app
#    e.g. hiddenly when you do "import kirie" in your app

nm=wiw

#%ATT: always hardcoded withou fallback -- to overcome chaining of different main apps
export KIRIE_MAINAPP="$nm"  # RENAME: KIRIE_ENTRYPOINT

# NOTE: don't override user settings, only fallback
set -o allexport
: "${WIW_AUTH_DIR:=${XDG_CACHE_HOME:-$HOME/.cache}/$nm/_auth}"
: "${WIW_TEMP_DIR:=${TMPDIR:-/tmp}/$nm}"
set +o allexport


if test "x${1-}" == "x--recache"; then
  exe="$nm"-xdg
  set -- "$nm"
elif test -z "${WIW_CACHE_DIR+x}" -o "x${1+${1#-}}" != "x${1-}"; then
  WIW_CACHE_DIR=$("$nm"-xdg "$nm")
  export WIW_CACHE_DIR
  exe="$nm"-cli
else
  cmd=${1:?Need full cmd in format: a/b/c}
  exe=${WIW_CACHE_DIR:?}/$cmd
  if ! test -f "$exe" -a -x "$exe" -a -s "$exe"; then
    >&2 echo "Err: not found cmd '$cmd'"
    exit 2
  fi
  shift
fi

exec "$exe" "$@"
